version: "3"
services:

  server:
    container_name: taxonify-webserver-test
    command: /bin/bash -c 'sleep 5 && python -m teamcity.unittestpy discover -s ./aquascope/tests -t. -v'
    image: "${WEBSERVER_IMAGE}"
    env_file:
      - ./mongodb_user_credentials.env
      - ./mongodb_root_credentials.env
      - ./user_authentication.env
      - ./storage_credentials.env
    environment:
      - TEST_STORAGE_SERVICE_CONFIG_FILE=/storage_service.yml
    volumes:
      - ./configs/test_docker/storage_service.yml:/storage_service.yml
    networks:
      - taxonify-test
    depends_on:
      - mongo-test
      - storage-emulator-test

  mongo-test:
    container_name: taxonify-mongo-test
    image: mongo:4.0
    env_file:
      - ./user_authentication.env
      - ./mongodb_root_credentials.env
      - ./mongodb_user_credentials.env
    expose:
      - 27017
    networks:
      - taxonify-test
    volumes:
      - ./docker/local_db/:/docker-entrypoint-initdb.d/:ro

  storage-emulator-test:
    container_name: taxonify-storage-emulator-test
    image: arafato/azurite
    environment:
      - executable=blob
    expose:
      - 10000
    networks:
      - taxonify-test

networks:
  taxonify-test:
    driver: bridge
