version: "3"
services:

  server:
    build:
      context: .
      dockerfile: docker/webserver/Dockerfile
    ports:
      - 80:80
    depends_on:
      - rabbitmq
      - mongo
    volumes:
      - ./webserver.log:/app/webserver.log
      - .:/app
    network_mode: host
    env_file:
      - celery.env
      - celery_consts.env
      - mongodb_user_credentials.env
      - user_authentication.env
      - storage_credentials.env

  rabbitmq:
    image: rabbitmq:3-management-alpine
    environment:
      - RABBITMQ_NODENAME=rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    env_file:
      - celery.env
      - celery_consts.env

  celery-worker:
    build:
      context: .
      dockerfile: docker/celery_worker/Dockerfile
    depends_on:
      - rabbitmq
    volumes:
      - ./logs:/app/logs
    env_file:
      - celery.env
      - celery_consts.env
      - mongodb_user_credentials.env
      - storage_credentials.env
    network_mode: host

  mongo:
    image: mongo:4
    env_file:
      - mongodb_root_credentials.env
      - mongodb_user_credentials.env
    ports:
      - 27017:27017
    volumes:
      - ./docker/local_db/:/docker-entrypoint-initdb.d/:ro
      - ./db_data:/data/db

  storage-emulator:
    image: arafato/azurite
    environment:
      - executable=blob
    ports:
      - 10000:10000

  swagger-ui:
    image: swaggerapi/swagger-ui
    ports:
      - 8080:8080
    environment:
      - SWAGGER_JSON=/app/swagger.yaml
    volumes:
      - ./swagger/swagger.yaml:/app/swagger.yaml

  swagger-editior:
    image: swaggerapi/swagger-editor
    ports:
      - 8081:8080
