openapi: 3.0.0
info:
  description: Aquascope Virtum API
  version: 0.1.0
  title: aquascope-virtum
  contact:
    email: aleksander.cieslak@microscopeit.com
servers:
  - url: 'http://localhost/'

paths:
  /user/login:
    post:
      description: 'Login user using username and password (in plaintext). Returns access_token and refresh_token'
      operationId: login
      tags:
        - User
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  access_token:
                    type: string
                  refresh_token:
                    type: string
        '400':
          description: 'Unknown arguments'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UnknownArgumentsResult'

        '401':
          description: 'Wrong credentials'
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        '500':
          description: 'Server error. Most likely wrong hash used for storing password is malformed'
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
  /user/refresh:
    post:
      description: 'Refreshing access_token using authorisation with refresh_token'
      operationId: refresh
      tags:
        - User
      security:
        - refreshBearerAuth: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  access_token:
                    type: string

  /sas:
    get:
      description: 'Obtains SAS, which is data access token. Obtained token should be appended to every `url` field from API response bodies'
      operationId: get_sas
      tags:
        - Sas
      security:
       - bearerAuth: []
      parameters:
        - name: destination
          description: Specifies SAS's destination. `processed` should be used to obtain data from `/items GET` respone. `upload` should be used to obtain access to upload. `download` should be used to obtain data from `/download/<id> GET` response.
          in: query
          required: true
          schema:
            type: string
            enum: [processed, upload, download]
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SasResult'

        '400':
          description: 'Invalid choice'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadSasResponses'
          examples:
            InvalidSasChoice:
              message:
                destination: <destination> is not a valid choice
            UnknownArgumentsResult:
              message: "Unknown arguments: <arguments>"

  /items:
    post:
      description: 'Updates data samples'
      operationId: post_items
      tags:
        - Items
      security:
       - bearerAuth: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ItemsUpdate'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ItemsUpdateResult'


    get:
      description: 'Obtains list of data samples that match provided query'
      operationId: get_items
      tags:
        - Items
      security:
        - bearerAuth: []
      parameters:
        - name: empire
          in: query
          required: false
          schema:
            type: string
            example: 'prokaryota'
        - name: kingdom
          in: query
          required: false
          schema:
            type: string
            example: 'Bacteria'
        - name: phylum
          in: query
          required: false
          schema:
            type: string
            example: 'Cyanobacteria'
        - name: class
          in: query
          required: false
          schema:
            type: string
            example: 'Cyanophyceae'
        - name: order
          in: query
          required: false
          schema:
            type: string
            example: 'Nostocales'
        - name: family
          in: query
          required: false
          schema:
            type: string
            example: 'Nostocaceae'
        - name: genus
          in: query
          required: false
          schema:
            type: string
            example: 'Anabaena'
        - name: species
          in: query
          required: false
          schema:
            type: string
            example: 'sp'
        - name: filename
          in: query
          required: false
          schema:
            type: string
            example: 'images_00000_SPC-EAWAG-5P0X-15433639.*'
        - name: dividing
          in: query
          required: false
          schema:
            type: array
            items:
              type: boolean
              nullable: true
        - name: dead
          in: query
          required: false
          schema:
            type: array
            items:
              type: boolean
              nullable: true
        - name: with_epiphytes
          in: query
          required: false
          schema:
            type: array
            items:
              type: boolean
              nullable: true
        - name: broken
          in: query
          required: false
          schema:
            type: array
            items:
              type: boolean
              nullable: true
        - name: colony
          in: query
          required: false
          schema:
            type: array
            items:
              type: boolean
              nullable: true
        - name: eating
          in: query
          required: false
          schema:
            type: array
            items:
              type: boolean
              nullable: true
        - name: multiple_species
          in: query
          required: false
          schema:
            type: array
            items:
              type: boolean
              nullable: true
        - name: cropped
          in: query
          required: false
          schema:
            type: array
            items:
              type: boolean
              nullable: true
        - name: male
          in: query
          required: false
          schema:
            type: array
            items:
              type: boolean
              nullable: true
        - name: female
          in: query
          required: false
          schema:
            type: array
            items:
              type: boolean
              nullable: true
        - name: juvenile
          in: query
          required: false
          schema:
            type: array
            items:
              type: boolean
              nullable: true
        - name: adult
          in: query
          required: false
          schema:
            type: array
            items:
              type: boolean
              nullable: true
        - name: with_eggs
          in: query
          required: false
          schema:
            type: array
            items:
              type: boolean
              nullable: true
        - name: acquisition_time_start
          in: query
          required: false
          schema:
            type: string
            example: '2019-01-26 00:00:00.000Z'
        - name: acquisition_time_end
          in: query
          required: false
          schema:
            type: string
            example: '2019-01-27 00:00:00.000Z'

      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ItemsQueryResult'
        '400':
          description: Unknown arguments
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UnknownArgumentsResult'


components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
    refreshBearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    Item:
      properties:
        _id:
          type: string
        filename:
          type: string
        extension:
          type: string
        group_id:
          type: string
        empire:
          type: string
        kingdom:
          type: string
        phylum:
          type: string
        class:
          type: string
        order:
          type: string
        family:
          type: string
        genus:
          type: string
        species:
          type: string
        dividing:
          type: boolean
          nullable: true
        dead:
          type: boolean
          nullable: true
        with_epiphytes:
          type: boolean
          nullable: true
        broken:
          type: boolean
          nullable: true
        colony:
          type: boolean
          nullable: true
        eating:
          type: boolean
          nullable: true
        multiple_species:
          type: boolean
          nullable: true
        cropped:
          type: boolean
          nullable: true
        male:
          type: boolean
          nullable: true
        female:
          type: boolean
          nullable: true
        juvenile:
          type: boolean
          nullable: true
        adult:
          type: boolean
          nullable: true
        with_eggs:
          type: boolean
          nullable: true
        acquisition_time:
          type: string
          format: date-time
        image_width:
          type: integer
        image_height:
          type: integer
    ListOfItems:
      type: array
      items:
        $ref: '#/components/schemas/Item'
    ListOfUrls:
      type: array
      items:
        type: string
        format: url
    ItemsQueryResult:
      properties:
        items:
          $ref: '#/components/schemas/ListOfItems'
        urls:
          $ref: '#/components/schemas/ListOfUrls'
    UnknownArgumentsResult:
      type: object
      properties:
        message:
          type: array
          items:
            type: object
            properties:
              parameters:
                type: string
              errors:
                type: array
                items:
                  type: string
    ItemsUpdate:
      type: array
      items:
        properties:
          current:
              $ref: '#/components/schemas/Item'
          update:
              $ref: '#/components/schemas/Item'
    ItemsUpdateResult:
      properties:
        matched:
          type: integer
        modified:
          type: integer
    SasResult:
      properties:
        token:
          type: string
          format: url
    InvalidSasChoice:
      properties:
        message:
          properties:
            destination:
              type: string
              example: '<destination> is not a valid choice'
    BadSasResponses:
      description: SwaggerUI doesn't know how to render oneOf
      type: object
      oneOf:
        - $ref: '#/components/schemas/InvalidSasChoice'
        - $ref: '#/components/schemas/UnknownArgumentsResult'


tags:
  - name: User
    description: Endpoints responsible for login and token management
  - name: Items
    description: Endpoints responsible for items (data samples) management
  - name: Sas
    description: Endpoints responsible for SAS tokens (data access tokens) management
